### ISSUE TITLE
Change the Contribution to md and style it 

### ISSUE THREAD

**Issue by mrigaankzoro** [mrigaankzoro/Hacktoberfest24#1]
Change the Contribution to md and style it  
use md style and make it look nice

**Comment by shash369** [comment]
I hope this message finds you well. I am writing to kindly request the opportunity to be assigned to theproject as part of Hacktoberfest 2024. I am eager to contribute and believe that my skills and experience would add value to the project.

**Comment by MRIGAANKSh** [comment]
please assign me this pls pls pls our names are also same

**Comment by mrigaankzoro** [comment]
done bro make it look better the contributor .md

**Comment by MRIGAANKSh** [comment]
thanks bro

**Comment by mrigaankzoro** [comment]
this issue is done MRIGAANKSh
