### ISSUE TITLE
Can i contribute an dsa question into it

### ISSUE THREAD

**Issue by AthulKkumar** [mrigaankzoro/Hacktoberfest24#10]

**Comment by mrigaankzoro** [comment]
do it bro

**Comment by AthulKkumar** [comment]
Permission got denied to push bro ,need the permission for it to push it the repo

**Comment by KirtiPandey19** [comment]
Hello @anuragverma108,
I am actively participating in Hacktoberfest 2024. I came across your repository, and I am very interested in contributing to it. I would love to work on this repo or any other task where you feel I can provide value. So Please assign me this repo.
