### ISSUE TITLE
Want to add reverse algorithm in cpp 

### ISSUE THREAD

**Issue by ishant025** [mrigaankzoro/Hacktoberfest24#16]
please assign this to me

**Comment by atomnoid** [comment]
assign this to me please

**Comment by mrigaankzoro** [comment]
Done bro

**Comment by mrigaankzoro** [comment]
Contribute to my project [https://www.linkedin.com/posts/mrigaank-sharma-955357295_hacktoberfest-hacktoberfest24-github-activity-7248674545883066368-zQNQ?utm_source=share&utm_medium=member_android](url)
