### ISSUE TITLE
Check Prime in C++

### ISSUE THREAD

**Issue by Amisha2093** [mrigaankzoro/Hacktoberfest24#20]
**Description:**

Given a number and determine if the number is Prime or Not Prime using the Most Efficient Approach.

**Comment by Amisha2093** [comment]
Hi @mrigaankzoro,

Can you please assign this issue to me, under **hacktoberfest24**.

**Comment by Amisha2093** [comment]
Hi @mrigaankzoro,

Can you please review and merge my PR #21 under hacktoberfest24.

**Comment by mrigaankzoro** [comment]
Done

**Comment by Amisha2093** [comment]
Hi @mrigaankzoro,

I am getting this repository is excluded from hacktoberfest24, can you please help me solve this and get my contribution counted.

<img width="888" alt="image" src="https://github.com/user-attachments/assets/98dd015b-a6b8-49e4-b159-a1bcd91c450c">
