### ISSUE TITLE
"Longest Substring Without Repeating Characters" in cpp

### ISSUE THREAD

**Issue by Tejkaur04** [mrigaankzoro/Hacktoberfest24#23]
Given a string s , we have to  find the length of the longest substring without repeating characters
For Example:

**Input:**
s = "abcabcbb"
**Output:** 3

**Explanation:** The answer is "abc", with the length of 3.

**Comment by Tejkaur04** [comment]
@mrigaankzoro Kindly assign me this issue under hacktoberfest , i can work on this problem using an appropriate approach.

**Comment by mrigaankzoro** [comment]
Done

**Comment by Tejkaur04** [comment]
can you please label issue #35 as hacktoberfest , on the official website it is showing that my PR has not been accepted or merged

**Comment by mihir-k64** [comment]
can you assign it to me under hacktoberfest tag please will give u best efficent approach

**Comment by pratyush07-hub** [comment]
kindly assign me this issue
