### ISSUE TITLE
To add container with most water

### ISSUE THREAD

**Issue by moksha-hub** [mrigaankzoro/Hacktoberfest24#30]
hello @mrigaankzoro 
can you assign it to me as well as with hacktoberfest label
Thank you

**Comment by mrigaankzoro** [comment]
Done

**Comment by mihir-k64** [comment]
hello @mrigaankzoro can you assign it to me as well with hacktoberfest label 
thank you

**Comment by Pariyul** [comment]
hey i want to contribute in this , can you please assign it to me under hacktober fest.
