### ISSUE TITLE
To add Buy and sell stock problem

### ISSUE THREAD

**Issue by moksha-hub** [mrigaankzoro/Hacktoberfest24#40]
hello @mrigaankzoro i would i like to add a problem by contributing it 
the problem is buy and sell stock problem 
can you assign it to me along with label of hacktoberfest 
thank you

**Comment by mrigaankzoro** [comment]
done

**Comment by Pariyul** [comment]
hey i want to contribute in this , can you please assign it to me under hacktober fest.
